#!/bin/bash

echo "Starting Server Setup..."

echo "Updating system..."
sudo apt update -y

echo "Installing Nginx..."
sudo apt install nginx -y

echo "Starting Nginx service..."
sudo systemctl start nginx

echo "Enabling Nginx on boot..."
sudo systemctl enable nginx